# ===============================
# SERVER
# ===============================
server.port=8082
spring.application.name=booking-service

# ===============================
# SECURITY (Basic Auth)
# ===============================
spring.security.user.name=booking
spring.security.user.password=booking123
spring.security.user.roles=USER

# ===============================
# DATABASE (H2 - DEV)
# ===============================
spring.datasource.url=jdbc:h2:mem:bookingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# EUREKA CLIENT
# ===============================
# E?er discovery-server'da user/password varsa:
eureka.client.service-url.defaultZone=http://admin:admin123@localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
logging.level.org.springframework=DEBUG
logging.level.com.eventplanner=DEBUG