############################################
# SERVER
############################################
server.port=8080

############################################
# APPLICATION
############################################
spring.application.name=api-gateway

############################################
# EUREKA CLIENT
############################################
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://admin:admin123@localhost:8761/eureka

############################################
# SPRING CLOUD GATEWAY (DISCOVERY)
############################################
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

############################################
# ACTUATOR
############################################
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

############################################
# SPRING SECURITY (BASIC AUTH)
############################################
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN
